name: Feature Request
description: Suggest an idea for this project
title: '[FEATURE]: '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: A clear and concise description of what the problem is
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: possible-solution
    attributes:
      label: Possible Solution
      description: A clear and concise description of what you want to happen (optional)
      placeholder: Describe your proposed solution (optional)
    validations:
      required: false
